# Generated by Django 6.0.2 on 2026-02-06 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(help_text='Key used to guarantee idempotent payment creation', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('captured', 'Captured')], default='captured', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Original payment amount', max_digits=12)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, help_text='Fee charged by the platform', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after platform fees', max_digits=12)),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('card', 'Card')], max_length=10)),
                ('installments', models.PositiveSmallIntegerField(help_text='Number of installments')),
                ('currency', models.CharField(max_length=3)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['idempotency_key'], name='payments_idempot_1c73ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Event type (e.g. payment_captured)', max_length=50)),
                ('payload', models.JSONField(help_text='Event payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='app.payment')),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['payment'], name='outbox_even_payment_70ed62_idx'), models.Index(fields=['type'], name='outbox_even_type_b0138b_idx'), models.Index(fields=['status'], name='outbox_even_status_90eac7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(help_text='Identifier of the payment recipient', max_length=255)),
                ('role', models.CharField(help_text='Role of the recipient (producer, affiliate, etc)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount assigned to this recipient', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='app.payment')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['payment'], name='ledger_entr_payment_8c0152_idx'), models.Index(fields=['recipient_id'], name='ledger_entr_recipie_42c77e_idx')],
            },
        ),
    ]
